import difflib

indices = [
    "Affiche de carte au trésor",
    "Aiguille à coudre",
    "Ancre dorée",
    "Anneau d'or",
    "Arbre à épines",
    "Arbre à moitié coupé",
    "Arbre à trous",
    "Arbre ensanglanté",
    "Arbre glacé",
    "Arche naturelle",
    "Balançoire macabre",
    "Ballons en forme de coeur",
    "Bannière bontarienne déchirée",
    "Bannière brâkmarienne déchirée",
    "Barque coulée",
    "Blé noir et blanc",
    "Bombe coeur",
    "Bonbon bleu",
    "Bougie dans un trou",
    "Bonhomme de neige fondu",
    "Boule dorée de marin",
    "Bouton de couture",
    "Buisson poupée sadida",
    "Cadran solaire",
    "Cairn",
    "Canard en plastique",
    "Canne à kebab",
    "Cocotte origami",
    "Corail avec des dents",
    "Carapace de tortue",
    "Casque à cornes",
    "Ceinture cloutée",
    "Champignon rayé",
    "Chapeau dé",
    "Chaussette à pois",
    "Clef dorée",
    "Coquillage à pois",
    "Corne de likrone",
    "Crâ cramé",
    "Crâne dans un trou",
    "Crâne de Crâ",
    "Crâne de cristal",
    "Crâne de likrone",
    "Crâne de likrone dans la glace",
    "Crâne de renne",
    "Crâne de Roublard",
    "Croix en pierre brisée",
    "Dé en glace",
    "Dessin au pipi dans la neige",
    "Dessin de croix dans un cercle",
    "Dessin dragodinde",
    "Dessin koalak",
    "Dofus en bois",
    "Dolmen",
    "Échelle cassée",
    "Éolienne à quatre pales",
    "Épouvantail à pipe",
    "Étoile en papier plié",
    "Étoile jaune peinte",
    "Fer à cheval",
    "Filon de cristaux multicolores",
    "Flèche dans une pomme",
    "Fleur de nénuphar bleue",
    "Fleurs smiley",
    "Framboisier",
    "Girouette dragodinde",
    "Grand coquillage cassé",
    "Gravure d'épée",
    "Gravure d'aile",
    "Gravure d'arakne",
    "Gravure d'étoile",
    "Gravure d'oeil",
    "Gravure de bouftou",
    "Gravure de boule de poche",
    "Gravure de chacha",
    "Gravure de clef",
    "Cactus sans épines",
    "Cactus à fleur bleue",
    "Gravure de coeur",
    "Gravure de crâne",
    "Gravure de croix",
    "Gravure de Dofus",
    "Gravure de dragodinde",
    "Gravure de fantôme",
    "Gravure de Firefoux",
    "Gravure de flèche",
    "Gravure de fleur",
    "Gravure de Gelax",
    "Gravure de Kama",
    "Gravure de logo Ankama",
    "Gravure de lune",
    "Gravure de papatte",
    "Gravure de rose des vents",
    "Gravure de soleil",
    "Gravure de spirale",
    "Gravure de symbole de quête",
    "Gravure de symbole égal",
    "Gravure de tofu",
    "Gravure de wabbit",
    "Gravure de wukin",
    "Grelot",
    "Hache brisée",
    "Kaliptus à fleurs jaunes",
    "Kaliptus coupé",
    "Kaliptus grignoté",
    "Kama peint",
    "Lampion bleu",
    "Langue dans un trou",
    "Lanterne au crâne luminescent",
    "Logo Ankama peint",
    "Marionnette",
    "Menottes",
    "Minouki",
    "Moufles jaunes",
    "Moufles rouges",
    "Niche dans une caisse",
    "Oeil de shushu peint",
    "Oeuf dans un trou",
    "Ornement flocon",
    "Os dans la lave",
    "Obélisque enfoui",
    "Paire de lunettes",
    "Palmier à feuilles carrées",
    "Palmier à feuilles déchirées",
    "Palmier à pois",
    "Palmier peint à rayures",
    "Palmier peint d'un chacha",
    "Palmier surchargé de noix de coco",
    "Panneau nonosse",
    "Peinture de Dofus",
    "Peluche de likrone",
    "Phorreur sournois / baveux / chafouin / fourbe",
    "Pioche plantée",
    "Poisson grillé embroché",
    "Poupée koalak",
    "Queue d'Osamodas",
    "Rocher à sédimentation verticale",
    "Rocher crâne",
    "Rocher dé",
    "Rocher Dofus",
    "Rocher percé",
    "Rocher taillé en arètes de poisson",
    "Rose des vents dorée",
    "Rose noire",
    "Ruban bleu noué",
    "Rune nimbos",
    "Sapin couché",
    "Serrure dorée",
    "Sève qui s'écoule",
    "Slip à petit coeur",
    "Soupe de bananagrumes",
    "Squelette d'Ouginak pendu",
    "Statue koalak",
    "Statue sidoa",
    "Statue wabbit",
    "Stèle chacha",
    "Sucre d'orge",
    "Symbole de quête peint",
    "Talisman en papier",
    "Tambour à rayures",
    "Tambour papatte",
    "Théière à rayures",
    "Tissu à carreaux noué",
    "Tombe gravée d'un bouclier",
    "Tombe inondée",
    "Tombe inondée de sang",
    "Torii cassé",
    "Trace de main en sang",
    "Tricycle",
    "Tube rempli de tofus"
]



def trouver_chaine_proche(cible):
    plus_proche = difflib.get_close_matches(cible, indices, n=1, cutoff=0.0)
    return plus_proche[0] if plus_proche else None